version: "3"

networks:
  loki:

volumes:
  logs:
  loki:
  grafana:

services:
  loki:
    image: grafana/loki:2.7.4
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    volumes:
       - loki:/loki
  
  ptsyslog:
    image: neolemarc/ptsyslog
    networks:
      - loki
    volumes:
      - logs:/var/log
    ports:
      - "514:514/udp"

  promtail:
    image: grafana/promtail:2.7.4
    volumes:
      - logs:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
    volumes:
      - grafana:/var/lib/grafana

